### ISSUE TITLE
Wrong link to payu.css

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/payulatam#5]
When I'm the front office, especially on the checkout tunnel, I get the following error in the console:

 ```
"NetworkError: 404 Not Found - http://localhost/var/www/html/PrestaShop/modules/payulatam/css/payu.css"
```

The path is no properly generated.

Regards

**Comment by jgarzonp** [comment]
Hi @Quetzacoalt91,

Could you give me any images about the error and the view where you are?, because I am looking for the error, but I have not found it.
